export { LocomotiveScrollComponent } from './LocomotiveScrollComponent/LocomotiveScrollComponent';
export { OrbitText } from './FirstSection/OrbitText/OrbitText';
export { Orbit } from './Orbit/Orbit';
export { FirstSection } from './FirstSection/FirstSection';
export { PreloadVideo } from './PreloadVideo/PreloadVideo';
export { Stars } from './Stars/Stars';
export { SecondSection } from './SecondSection/SecondSection';
export { ThirdSection } from './ThirdSection/ThirdSection';
export { FourthSection } from './FourthSection/FourthSection';
export { AstronautInBottle } from './AstronautInBottle/AstronautInBottle'
export { AnimatedPill } from './AnimatedPill/AnimatedPill';